export const DISABLE_STATS =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::DISABLE_STATS";
export const STATS_DISABLED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::STATS_DISABLED";
export const DISABLE_STATS_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::DISABLE_STATS_FAILED";
export const SET_AUDIO_ONLY_MODE =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_AUDIO_ONLY_MODE";
export const AUDIO_ONLY_MODE_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::AUDIO_ONLY_MODE_CHANGED";
export const SET_AUDIO_ONLY_MODE_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_AUDIO_ONLY_MODE_FAILED";
export const SET_COMPOSITOR_FIXED_PARTICIPANTS =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_COMPOSITOR_FIXED_PARTICIPANTS";
export const COMPOSITOR_FIXED_PARTICIPANTS_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::COMPOSITOR_FIXED_PARTICIPANTS_CHANGED";
export const SET_COMPOSITOR_FIXED_PARTICIPANTS_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_COMPOSITOR_FIXED_PARTICIPANTS_FAILED";
export const SET_CONNECTOR_API_LOGGING =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_CONNECTOR_API_LOGGING";
export const CONNECTOR_API_LOGGING_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::CONNECTOR_API_LOGGING_CHANGED";
export const SET_CONNECTOR_API_LOGGING_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_CONNECTOR_API_LOGGING_FAILED";
export const SET_SIMPLE_API_LOGGING =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_SIMPLE_API_LOGGING";
export const SIMPLE_API_LOGGING_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SIMPLE_API_LOGGING_CHANGED";
export const SET_SIMPLE_API_LOGGING_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_SIMPLE_API_LOGGING_FAILED";
export const SET_SIMULCAST =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_SIMULCAST";
export const SIMULCAST_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SIMULCAST_CHANGED";
export const SET_SIMULCAST_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_SIMULCAST_FAILED";
export const SET_TRANSPORT_CC =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_TRANSPORT_CC";
export const TRANSPORT_CC_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::TRANSPORT_CC_CHANGED";
export const SET_TRANSPORT_CC_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_TRANSPORT_CC_FAILED";
export const SET_UNIFIED_PLAN =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_UNIFIED_PLAN";
export const UNIFIED_PLAN_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::UNIFIED_PLAN_CHANGED";
export const SET_UNIFIED_PLAN_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_UNIFIED_PLAN_FAILED";
export const SET_AUTO_RECONNECT =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_AUTO_RECONNECT";
export const AUTO_RECONNECT_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::AUTO_RECONNECT_CHANGED";
export const SET_AUTO_RECONNECT_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_AUTO_RECONNECT_FAILED";
export const SET_PARTICIPANT_LIMIT =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_PARTICIPANT_LIMIT";
export const PARTICIPANT_LIMIT_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::PARTICIPANT_LIMIT_CHANGED";
export const SET_PARTICIPANT_LIMIT_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_PARTICIPANT_LIMIT_FAILED";
export const SET_MAX_RECONNECT_ATTEMPTS =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_MAX_RECONNECT_ATTEMPTS";
export const MAX_RECONNECT_ATTEMPTS_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::MAX_RECONNECT_ATTEMPTS_CHANGED";
export const SET_MAX_RECONNECT_ATTEMPTS_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_MAX_RECONNECT_ATTEMPTS_FAILED";
export const SET_RECONNECT_BACKOFF =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_RECONNECT_BACKOFF";
export const RECONNECT_BACKOFF_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::RECONNECT_BACKOFF_CHANGED";
export const SET_RECONNECT_BACKOFF_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SET_RECONNECT_BACKOFF_FAILED";
export const SHOW_STATS_OVERLAY =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SHOW_STATS_OVERLAY";
export const SHOW_STATS_OVERLAY_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SHOW_STATS_OVERLAY_CHANGED";
export const SHOW_STATS_OVERLAY_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::SHOW_STATS_OVERLAY_FAILED";
export const ADD_LOG_CATEGORY =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::ADD_LOG_CATEGORY";
export const ADD_LOG_CATEGORY_FAILED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::ADD_LOG_CATEGORY_FAILED";
export const LOG_LEVELS_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::LOG_LEVELS_CHANGED";
export const LOG_CATEGORIES_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::LOG_CATEGORIES_CHANGED";
export const ACTIVE_LOGS_CHANGED =
  "VIDYO_CONNECTOR::ADVANCED_SETTINGS::ACTIVE_LOGS_CHANGED";
