export const SET_EXT_DATA = "CONFIG::SET_EXT_DATA";
export const SET_EXT_DATA_SUCCEEDED = "CONFIG::SET_EXT_DATA_SUCCEEDED";
export const SET_EXT_DATA_FAILED = "CONFIG::SET_EXT_DATA_FAILED";
export const SET_URL_PARAMS = "CONFIG::SET_URL_PARAMS";
export const SET_PORTAL_FEATURES = "CONFIG::SET_PORTAL_FEATURES";
export const SET_COMPOSITOR_FIXED_PARTICIPANTS =
  "CONFIG::SET_COMPOSITOR_FIXED_PARTICIPANTS";
export const SET_COMPOSITOR_FIXED_PARTICIPANTS_FAILED =
  "CONFIG::SET_COMPOSITOR_FIXED_PARTICIPANTS_FAILED";
export const SEND_SMS = "CONFIG::SEND_SMS";
export const SEND_SMS_SUCCEEDED = "CONFIG::SEND_SMS_SUCCEEDED";
export const SEND_SMS_FAILED = "CONFIG::SEND_SMS_FAILED";
export const SET_STATISTICS_OVERLAY = "CONFIG::SET_STATISTICS_OVERLAY";
export const SET_STATISTICS_OVERLAY_SUCCEEDED =
  "CONFIG::SET_STATISTICS_OVERLAY_SUCCEEDED";
export const SET_STATISTICS_OVERLAY_FAILED =
  "CONFIG::SET_STATISTICS_OVERLAY_FAILED";

export const GET_CUSTOM_PARAMETERS = "CONFIG::GET_CUSTOM_PARAMETERS";
export const GET_CUSTOM_PARAMETERS_SUCCEEDED =
  "CONFIG::GET_CUSTOM_PARAMETERS_SUCCEEDED";
export const GET_CUSTOM_PARAMETERS_FAILED =
  "CONFIG::GET_CUSTOM_PARAMETERS_FAILED";

export const GET_GCP_SERVICES_LIST = "CONFIG::GET_GCP_SERVICES_LIST";
export const GET_GCP_SERVICES_LIST_SUCCEEDED =
  "CONFIG::GET_GCP_SERVICES_LIST_SUCCEEDED";
export const GET_GCP_SERVICES_LIST_FAILED =
  "CONFIG::GET_GCP_SERVICES_LIST_FAILED";
export const RESET_GCP_SERVICES_LIST = "CONFIG::RESET_GCP_SERVICES_LIST";

export const GET_ENDPOINT_BEHAVIOUR = "CONFIG::SET_ENDPOINT_BEHAVIOUR";
export const GET_ENDPOINT_BEHAVIOUR_SUCCEEDED =
  "CONFIG::SET_ENDPOINT_BEHAVIOUR_SUCCEEDED";
export const GET_ENDPOINT_BEHAVIOUR_FAILED =
  "CONFIG::SET_ENDPOINT_BEHAVIOUR_FAILED";

export const SET_JWT_TOKEN = "CONFIG::SET_JWT_TOKEN";
export const SET_REFRESH_TOKEN = "CONFIG::SET_REFRESH_TOKEN";
